# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_username', models.CharField(max_length=30, null=True)),
                ('res_password', models.CharField(max_length=30, null=True)),
                ('res_email', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
