# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='res_',
            new_name='res_id',
        ),
    ]
