# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageA', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
                ('imageB', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
                ('imageC', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
                ('imageD', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
                ('voice', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=20)),
            ],
        ),
    ]
