# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180410_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='DesA',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='DesB',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='DesC',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='DesD',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ques',
            name='question',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
