# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='tips',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
