# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-12 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_recom_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recom_guide',
        ),
    ]
